name: Android Instrumentation Tests

on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/android-instrumentation-tests.yml

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew :expo-updates:connectedAndroidTest
        working-directory: ./android